### PR TITLE
Add option to continue if an Error occurs in one section

### LINKED ISSUE #124: Handle VERGEN_GIT_* more gracefully if the source is not a git repo
Thanks for making `vergen` :+1: 

Followup of #101.

It's quite common for Linux distrubutions to build a package from a source tarball, and not the git repo of the package. In that situation, if the `"git"` feature is present, the `vergen(Config::default())` function in `build.rs` will Error, and no `VERGEN_*` variables will be set. Sadly, that also includes vergen variables from other features, like `VERGEN_BUILD_*` or `VERGEN_RUSTC_*`, which do not depend on git.

In #101, ignoring the Error `vergen()` returns and using `option_env!` later seems to have been okay, probably because the user was only interested in `VERGEN_GIT_*`. However, ignoring Errors does not feel nice :)

I can think of two ways around this:
- @rapiz1's suggestion: instead of failing completely, simply don't set corresponding Git env vars. 
- Or, provide a configuration option "allow-nonexistent" (name TBD) for the `Git` struct, to keep the old behavior but allow the new.

I'm not sure which I'd prefer, but I'm happy to implement whatever is decided :)

### PR DESCRIPTION
**Pull request by puzzlewolf**
Closes #124 

What has been done:
- Add a configuration option `skip_if_error` to the `build`, `git`, `rustc` and `sysinfo` features, to allow skipping a feature and continuing if an Error occurs. `configure_cargo` is not fallible, so the option wouldn't make sense there. 
- Emit a `cargo:warning` if an Error was skipped in this way.
- Add a test for `skip_if_error` for the `git` feature. This adds a new dependency `tempfile`, which is just needed for this one test of the `git` feature. Sadly, there is no way to define optional dev-dependencies (https://github.com/rust-lang/cargo/issues/1596), so I deactivated the `unused_crate_dependencies` lint.
- Add documentation for the option and mention `option_env!`.
- Fix two unrelated nits. 

Open questions:
-  I'm not sure if `skip_if_error` is a good name, please suggest a better one :)
- It would be nice to add tests for the other features, too. Do you have an idea how to make them Error?
- Is disabling `unused_crate_dependencies` okay for you? 
- If you prefer, I'll open a separate PR for the unrelated nits.
- Please tell me if you'd like the commits squashed :)

### CODE REVIEW

**Comment by puzzlewolf** [comment]
Hey, could you please [approve](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) the CI run? I'm a first-time contributor to this project, so GitHub prevents me from running CI (and rightly so) :)

**Comment by puzzlewolf** [comment]
Thank you :) No problem, I hope the vacation was nice :tropical_drink: 

I messed up formatting, sorry :sweat:

**Comment by CraZySacX** [comment]
That's why the check is there :).  I miss formatting all the time.

**Comment by puzzlewolf** [comment]
Thanks for merging :) :tada:

**Pull request merged**
