### PR TITLE
v8.0.0:  Re-write for the next version

### PR DESCRIPTION
**Pull request by CraZySacX**
### Release 8.0.0-beta.0 has been published
[`crates.io`](https://crates.io/crates/vergen/8.0.0-beta.0)
[`docs.rs`](https://docs.rs/vergen/8.0.0-beta.0/vergen/index.html)

Feel free to comment on this PR about the main goals outline below

- [x] Minimize the `vergen` footprint.  
    * Adopt an opt-in methodology rather than opt-out.
    * Move from `_mut` config to a builder pattern.
    * Default features empty
    * Support the ability to configure `vergen` to emit warnings rather than a hard build error.
- [x] Minimize the `vergen` compile time impact.  
    * `git2` is a large feature, add back support for command line `git` to help here.
    * Remove extraneous libraries that add fluff over functionality, i.e. `thiserror`
- [x] Allow for idempotent output.
    * There have been requests to force `vergen` output to be reproducible. See  #141 for more information on this.
    * Support environment variables like `SOURCE_DATE_EPOCH` that make reproducible easier.
    * Backport this to v7 and maybe v6?
- [x] `vergen` should compile and test from a source tarball
    * A missing `.git` directory is the current culprit here.
    * Backport this to v7 and maybe v6?

### CODE REVIEW

**Comment by Kerollmops** [comment]
Hey @CraZySacX,

Thank you very much for vergen we use it in Meilisearch and it works great! However, I was trying to update our dependencies to `enum-iterator` and was unable to bump to the _1.2.0_ one, we are stuck using _1.1.3_. Is there a particular reason why you are dependending on `~1.1.3` and not upgrading to the new version?

Thank you

**Comment by CraZySacX** [comment]
> Hey @CraZySacX,
> 
> Thank you very much for vergen we use it in Meilisearch and it works great! However, I was trying to update our dependencies to `enum-iterator` and was unable to bump to the _1.2.0_ one, we are stuck using _1.1.3_. Is there a particular reason [why you depend on `~1.1.3` and not upgrading to the new version](https://github.com/rustyhorde/vergen/blob/fbdd186fd50fcb50b5724fafaddb5aba2a67e4a6/Cargo.toml#LL31C17-L31C17)?
> 
> Thank you

The original reason was #132.   I'll check version 1.2.0 to see if they have removed that nightly only dependency.

**Comment by CraZySacX** [comment]
> > The original reason was #132. I'll check version 1.2.0 to see if they have removed that nightly only dependency.
> 
> Ho right! I understand. [It has been shipped in stable since 1.63, now](https://doc.rust-lang.org/stable/std/array/fn.from_fn.html).

Yep, seem good on stable now.  I'll push out a new v7 release here shortly.

**Comment by CraZySacX** [comment]
@Kerollmops   I've pushed out 7.5.0.   Had to bump the MSRV to 1.63 as well.

**Pull request merged**
